import { expect, test } from '@playwright/test';
import { buildUrl } from './helpers/boot-path.js';

test.skip(
    process.env.SMOKE_SUITE === 'production',
    'Module-mocked app specs need the Vite dev server'
);

function appUrl(baseURL, path) {
    const appBaseURL = process.env.SMOKE_APP_BASE_URL || baseURL;
    const url = new URL(buildUrl(appBaseURL, '/'));
    url.hash = path;
    return url.toString();
}

async function mockFriendProfileModules(page) {
    await page.addInitScript(() => {
        window.__friendProfileLikes = [];
    });
    await page.route(/\/src\/lib\/useAuth\.ts(\?.*)?$/, async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/javascript',
            body: `
                export function useAuth() {
                    const user = { uid: 'user-1', email: 'parent@example.com', displayName: 'Pat Parent', roles: ['parent'], parentOf: [] };
                    return {
                        user,
                        profile: { parentOf: [] },
                        loading: false,
                        error: null,
                        roles: user.roles,
                        isParent: true,
                        isCoach: false,
                        isAdmin: false,
                        isPlatformAdmin: false,
                        refresh: async () => {},
                        signOut: async () => {}
                    };
                }
            `
        });
    });
    await page.route(/\/src\/lib\/authService\.ts(\?.*)?$/, async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/javascript',
            body: `export function getRouteForUser() { return '/home'; }`
        });
    });
    await page.route(/\/src\/lib\/socialService\.ts(\?.*)?$/, async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/javascript',
            body: `
                const post = (id, title, createdAt, likes) => ({
                    id,
                    type: 'manual_post',
                    visibility: 'friends',
                    authorId: 'friend-1',
                    authorName: 'Jamie Friend',
                    authorPhotoUrl: null,
                    teamId: 'team-1',
                    teamName: 'Bears',
                    playerIds: [],
                    playerNames: [],
                    sourceType: null,
                    sourceId: null,
                    title,
                    detail: 'A friend-visible update',
                    caption: title === 'Season opener' ? 'Proud of this team.' : null,
                    media: [],
                    route: null,
                    href: null,
                    createdAt: new Date(createdAt),
                    reactionCounts: { like: likes },
                    commentCount: 0,
                    viewerHasLiked: false,
                    hidden: false,
                    autoGenerated: false
                });
                export async function loadFriendProfile() {
                    return {
                        userId: 'friend-1',
                        name: 'Jamie Friend',
                        photoUrl: null,
                        sharedTeamNames: ['Bears'],
                        isSelf: false,
                        posts: [
                            post('post-new', 'Season opener', '2026-07-17T12:00:00Z', 2),
                            post('post-old', 'First practice', '2026-07-16T12:00:00Z', 0)
                        ]
                    };
                }
                export async function reactToSocialPost(postId) {
                    window.__friendProfileLikes.push(postId);
                    return { liked: true, count: 3 };
                }
            `
        });
    });
}

test.describe('friend-visible profile', () => {
    test.use({ viewport: { width: 390, height: 844 }, hasTouch: true });

    test('renders the profile timeline and persists the like interaction', async ({ page, baseURL }) => {
        await mockFriendProfileModules(page);
        await page.goto(appUrl(baseURL, '/people/friend-1'), { waitUntil: 'domcontentloaded' });

        await expect(page.getByRole('heading', { name: 'Jamie Friend' })).toBeVisible({ timeout: 15000 });
        await expect(page.getByText('Connected through Bears')).toBeVisible();
        await expect(page.getByRole('heading', { name: 'Season opener' })).toBeVisible();
        await expect(page.getByRole('heading', { name: 'First practice' })).toBeVisible();

        await page.getByRole('button', { name: 'Like post, 2 likes' }).click();

        await expect(page.getByRole('button', { name: 'Unlike post, 3 likes' })).toBeVisible();
        expect(await page.evaluate(() => window.__friendProfileLikes)).toEqual(['post-new']);
    });
});
