import {
  getEventDetailPath,
  type ParentHomeModel,
  type ParentHomePlayer,
  type ParentHomeTeam
} from './homeLogic';
import {
  formatEventDateLabel,
  formatEventTimeLabel,
  getScheduleTitle,
  type ParentScheduleEvent
} from './scheduleLogic';

export type SocialPostType =
  | 'game_recap'
  | 'player_moment'
  | 'team_media'
  | 'practice_packet'
  | 'upcoming_game'
  | 'achievement'
  | 'manual_post';

export type SocialVisibility =
  | 'household'
  | 'team'
  | 'friends'
  | 'friends_and_team'
  | 'public_profile';

export type SocialFeedFilter = 'all' | 'friends' | 'teams' | 'players' | 'highlights' | 'opportunities';

export type FriendshipStatus = 'none' | 'pending' | 'accepted' | 'declined' | 'removed' | 'blocked';

export type SocialPostPresetId = 'player' | 'game' | 'photo' | 'practice' | 'achievement';

export type SocialMedia = {
  type: 'image' | 'video';
  url: string;
  name?: string | null;
  thumbnailUrl?: string | null;
};

export type SocialFeedItem = {
  id: string;
  type: SocialPostType;
  visibility: SocialVisibility;
  authorId: string;
  authorName: string;
  authorPhotoUrl?: string | null;
  teamId?: string | null;
  teamName?: string | null;
  playerIds: string[];
  playerNames: string[];
  sourceType?: string | null;
  sourceId?: string | null;
  title: string;
  detail: string;
  caption?: string | null;
  media: SocialMedia[];
  route?: string | null;
  href?: string | null;
  createdAt: Date;
  reactionCounts: Record<string, number>;
  commentCount: number;
  hidden?: boolean;
  autoGenerated?: boolean;
};

export type SocialFriend = {
  id: string;
  userId: string;
  name: string;
  email?: string | null;
  photoUrl?: string | null;
  sharedTeamIds: string[];
  sharedTeamNames: string[];
  status: FriendshipStatus;
  requesterId?: string | null;
  recipientId?: string | null;
};

export type SocialHomeModel = {
  feedItems: SocialFeedItem[];
  friends: SocialFriend[];
  suggestions: SocialFriend[];
  incomingRequests: SocialFriend[];
  outgoingRequests: SocialFriend[];
  friendshipsError: string | null;
  metrics: {
    feedItems: number;
    friends: number;
    incomingRequests: number;
    suggestions: number;
  };
};

export const socialFeedFilters: Array<{ id: SocialFeedFilter; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'friends', label: 'Friends' },
  { id: 'teams', label: 'Teams' },
  { id: 'players', label: 'Players' },
  { id: 'highlights', label: 'Highlights' },
  { id: 'opportunities', label: 'Opportunities' }
];

export const socialVisibilityOptions: Array<{ id: SocialVisibility; label: string; detail: string }> = [
  { id: 'team', label: 'Team', detail: 'Visible to members of the selected team.' },
  { id: 'friends', label: 'Friends', detail: 'Visible to accepted ALL PLAYS friends.' },
  { id: 'friends_and_team', label: 'Friends + team', detail: 'Visible to friends and selected team members.' },
  { id: 'household', label: 'Household', detail: 'Visible to linked family only.' },
  { id: 'public_profile', label: 'Public profile', detail: 'Only for opted-in athlete/profile shares.' }
];

export const socialPostPresets: Array<{
  id: SocialPostPresetId;
  type: SocialPostType;
  label: string;
  shortLabel: string;
  detail: string;
  prompt: string;
  defaultVisibility: SocialVisibility;
  prefersPlayer: boolean;
  requiresMedia?: boolean;
  suggestions: string[];
}> = [
  {
    id: 'player',
    type: 'player_moment',
    label: 'Player moment',
    shortLabel: 'Moment',
    detail: 'Share a quick highlight for one player.',
    prompt: 'What stood out today?',
    defaultVisibility: 'friends',
    prefersPlayer: true,
    suggestions: [
      'Proud of the effort today.',
      'Big improvement this week.',
      'Great teamwork in a big moment.'
    ]
  },
  {
    id: 'game',
    type: 'game_recap',
    label: 'Game recap',
    shortLabel: 'Recap',
    detail: 'Post a short team update after a game.',
    prompt: 'How did the game go?',
    defaultVisibility: 'friends_and_team',
    prefersPlayer: false,
    suggestions: [
      'Hard fought game today.',
      'Great team win today.',
      'Lots to build on from this one.'
    ]
  },
  {
    id: 'photo',
    type: 'team_media',
    label: 'Photo or video',
    shortLabel: 'Media',
    detail: 'Add a photo or video with a caption.',
    prompt: 'Add a caption for the photo or video.',
    defaultVisibility: 'friends_and_team',
    prefersPlayer: false,
    requiresMedia: true,
    suggestions: [
      'Photos from today.',
      'Team energy was great.',
      'A few moments worth saving.'
    ]
  },
  {
    id: 'practice',
    type: 'practice_packet',
    label: 'Practice update',
    shortLabel: 'Practice',
    detail: 'Call out a packet, drill, or focus area.',
    prompt: 'What should families know before practice?',
    defaultVisibility: 'team',
    prefersPlayer: false,
    suggestions: [
      'Practice packet is ready.',
      'Focus work for the week is posted.',
      'Good reps coming up at practice.'
    ]
  },
  {
    id: 'achievement',
    type: 'achievement',
    label: 'Achievement',
    shortLabel: 'Achievement',
    detail: 'Celebrate a milestone or season best.',
    prompt: 'What milestone should be celebrated?',
    defaultVisibility: 'friends',
    prefersPlayer: true,
    suggestions: [
      'Milestone unlocked.',
      'New season best.',
      'A moment worth celebrating.'
    ]
  }
];

export function getSocialPostPresetForType(type: SocialPostType) {
  return socialPostPresets.find((preset) => preset.type === type) || socialPostPresets[0];
}

export function emptySocialHome(): SocialHomeModel {
  return {
    feedItems: [],
    friends: [],
    suggestions: [],
    incomingRequests: [],
    outgoingRequests: [],
    friendshipsError: null,
    metrics: {
      feedItems: 0,
      friends: 0,
      incomingRequests: 0,
      suggestions: 0
    }
  };
}

export function toSocialDate(value: any): Date {
  if (value instanceof Date && !Number.isNaN(value.getTime())) return value;
  if (typeof value?.toDate === 'function') {
    const date = value.toDate();
    if (date instanceof Date && !Number.isNaN(date.getTime())) return date;
  }
  if (typeof value?.seconds === 'number') return new Date(value.seconds * 1000);
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? new Date(0) : parsed;
}

export function getSocialTypeLabel(type: SocialPostType) {
  return {
    game_recap: 'Game recap',
    player_moment: 'Player moment',
    team_media: 'Team media',
    practice_packet: 'Practice packet',
    upcoming_game: 'Upcoming game',
    achievement: 'Achievement',
    manual_post: 'Post'
  }[type] || 'Post';
}

export function getSocialVisibilityLabel(visibility: SocialVisibility) {
  return socialVisibilityOptions.find((option) => option.id === visibility)?.label || 'Team';
}

export function buildFriendshipId(userIdA: string, userIdB: string) {
  return [String(userIdA || '').trim(), String(userIdB || '').trim()]
    .filter(Boolean)
    .sort()
    .join('__');
}

export function getFriendshipStatusForUser(friendship: any, currentUserId: string): FriendshipStatus {
  const status = String(friendship?.status || 'none') as FriendshipStatus;
  if (status === 'blocked') return 'blocked';
  if (status === 'accepted' || status === 'declined' || status === 'removed') return status;
  if (status === 'pending') return 'pending';
  return 'none';
}

export function normalizeSocialFriend(candidate: any, currentUserId: string, friendship?: any): SocialFriend | null {
  const userId = String(candidate?.uid || candidate?.id || candidate?.userId || '').trim();
  if (!userId || userId === currentUserId) return null;
  const fullName = String(candidate?.fullName || candidate?.displayName || candidate?.name || '').trim();
  const email = String(candidate?.email || '').trim();
  const memberIds = Array.isArray(friendship?.memberIds) ? friendship.memberIds : [];
  return {
    id: friendship?.id || buildFriendshipId(currentUserId, userId) || userId,
    userId,
    name: fullName || email || 'ALL PLAYS user',
    email: email || null,
    photoUrl: candidate?.photoUrl || candidate?.photoURL || null,
    sharedTeamIds: Array.isArray(candidate?.sharedTeamIds) ? candidate.sharedTeamIds.map(String) : [],
    sharedTeamNames: Array.isArray(candidate?.sharedTeamNames) ? candidate.sharedTeamNames.map(String) : [],
    status: friendship ? getFriendshipStatusForUser(friendship, currentUserId) : 'none',
    requesterId: friendship?.requesterId || null,
    recipientId: friendship?.recipientId || (memberIds.find((id: string) => id !== currentUserId) || userId)
  };
}

export function isIncomingFriendRequest(friend: SocialFriend, currentUserId: string) {
  return friend.status === 'pending' && friend.recipientId === currentUserId;
}

export function isOutgoingFriendRequest(friend: SocialFriend, currentUserId: string) {
  return friend.status === 'pending' && friend.requesterId === currentUserId;
}

export function categorizeFriends(friends: SocialFriend[], currentUserId: string) {
  const active = friends.filter((friend) => friend.status === 'accepted');
  const incomingRequests = friends.filter((friend) => isIncomingFriendRequest(friend, currentUserId));
  const outgoingRequests = friends.filter((friend) => isOutgoingFriendRequest(friend, currentUserId));
  return { active, incomingRequests, outgoingRequests };
}

export function buildSocialHomeModel({
  feedItems,
  friendshipFriends,
  suggestions,
  currentUserId,
  friendshipsError = null
}: {
  feedItems: SocialFeedItem[];
  friendshipFriends: SocialFriend[];
  suggestions: SocialFriend[];
  currentUserId: string;
  friendshipsError?: string | null;
}): SocialHomeModel {
  const { active, incomingRequests, outgoingRequests } = categorizeFriends(friendshipFriends, currentUserId);
  const activeIds = new Set(active.map((friend) => friend.userId));
  const requestedIds = new Set([...incomingRequests, ...outgoingRequests].map((friend) => friend.userId));
  const cleanSuggestions = suggestions
    .filter((friend) => friend.status === 'none')
    .filter((friend) => !activeIds.has(friend.userId) && !requestedIds.has(friend.userId))
    .slice(0, 8);
  const sortedFeedItems = sortSocialFeedItems(feedItems).slice(0, 80);

  return {
    feedItems: sortedFeedItems,
    friends: active,
    suggestions: cleanSuggestions,
    incomingRequests,
    outgoingRequests,
    friendshipsError,
    metrics: {
      feedItems: sortedFeedItems.length,
      friends: active.length,
      incomingRequests: incomingRequests.length,
      suggestions: cleanSuggestions.length
    }
  };
}

export function sortSocialFeedItems(items: SocialFeedItem[]) {
  return items.slice().sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
}

export function mergeSocialFeedItems(...itemLists: SocialFeedItem[][]) {
  const byId = new Map<string, SocialFeedItem>();
  itemLists.flat().forEach((item) => {
    if (!item?.id) return;
    byId.set(item.id, item);
  });
  return sortSocialFeedItems([...byId.values()]);
}

export function filterSocialFeedItems(items: SocialFeedItem[], filter: SocialFeedFilter) {
  if (filter === 'opportunities') return [];
  if (filter === 'all') return items;
  if (filter === 'friends') return items.filter((item) => item.visibility === 'friends' || item.visibility === 'friends_and_team');
  if (filter === 'teams') return items.filter((item) => Boolean(item.teamId) || item.visibility === 'team' || item.visibility === 'friends_and_team');
  if (filter === 'players') return items.filter((item) => item.playerIds.length > 0 || item.type === 'player_moment' || item.type === 'achievement');
  if (filter === 'highlights') return items.filter((item) => ['game_recap', 'team_media', 'achievement'].includes(item.type) || item.media.length > 0);
  return items;
}

export function buildDerivedSocialFeedItems(home: ParentHomeModel, authorId: string, authorName: string, now = new Date()): SocialFeedItem[] {
  const upcoming = (home.upcomingEvents || []).slice(0, 5).map((event) => eventToFeedItem(event, authorId, authorName));
  const packetItems = (home.upcomingEvents || [])
    .filter((event) => event.type === 'practice' && event.practiceHomePacketSummary)
    .slice(0, 3)
    .map((event) => practicePacketToFeedItem(event, authorId, authorName));
  const playerItems = (home.players || [])
    .filter((player) => player.nextEvent || player.rsvpNeeded || player.packetsReady)
    .slice(0, 4)
    .map((player) => playerToFeedItem(player, authorId, authorName, now));
  const teamItems = (home.teams || [])
    .filter((team) => team.unreadCount > 0 || team.nextEvent)
    .slice(0, 4)
    .map((team) => teamToFeedItem(team, authorId, authorName, now));

  return mergeSocialFeedItems(upcoming, packetItems, playerItems, teamItems);
}

function eventToFeedItem(event: ParentScheduleEvent, authorId: string, authorName: string): SocialFeedItem {
  return {
    id: `derived:upcoming:${event.teamId}:${event.id}:${event.childId || 'team'}`,
    type: 'upcoming_game',
    visibility: 'team',
    authorId,
    authorName,
    teamId: event.teamId,
    teamName: event.teamName,
    playerIds: event.childId ? [event.childId] : [],
    playerNames: event.childName ? [event.childName] : [],
    sourceType: 'event',
    sourceId: event.id,
    title: getScheduleTitle(event),
    detail: `${event.teamName} · ${formatEventDateLabel(event.date)} ${formatEventTimeLabel(event.date)} · ${event.location || 'TBD'}`,
    caption: event.type === 'practice' ? 'Practice is coming up.' : 'Game day is coming up.',
    media: [],
    route: getEventDetailPath(event),
    createdAt: event.date,
    reactionCounts: {},
    commentCount: 0,
    autoGenerated: true
  };
}

function practicePacketToFeedItem(event: ParentScheduleEvent, authorId: string, authorName: string): SocialFeedItem {
  return {
    ...eventToFeedItem(event, authorId, authorName),
    id: `derived:packet:${event.teamId}:${event.id}:${event.childId || 'team'}`,
    type: 'practice_packet',
    title: 'Practice packet ready',
    detail: `${event.childName || event.teamName} · ${event.practiceHomePacketSummary}`,
    caption: 'Packet is ready to review before practice.',
    route: getEventDetailPath(event, 'game')
  };
}

function playerToFeedItem(player: ParentHomePlayer, authorId: string, authorName: string, now: Date): SocialFeedItem {
  const actionCount = player.rsvpNeeded + player.packetsReady + player.openAssignments + (player.unreadCount > 0 ? 1 : 0);
  return {
    id: `derived:player:${player.teamId}:${player.playerId}`,
    type: actionCount > 0 ? 'player_moment' : 'achievement',
    visibility: 'friends',
    authorId,
    authorName,
    teamId: player.teamId,
    teamName: player.teamName,
    playerIds: [player.playerId],
    playerNames: [player.playerName],
    sourceType: 'player',
    sourceId: player.playerId,
    title: `${player.playerName}'s ALL PLAYS update`,
    detail: player.nextEvent ? `${player.teamName} · ${getScheduleTitle(player.nextEvent)}` : `${player.teamName} · ${actionCount} open item${actionCount === 1 ? '' : 's'}`,
    caption: actionCount > 0 ? `${actionCount} item${actionCount === 1 ? '' : 's'} to keep ${player.playerName} ready.` : 'Season progress is up to date.',
    media: [],
    route: `/players/${encodeURIComponent(player.teamId)}/${encodeURIComponent(player.playerId)}`,
    createdAt: player.nextEvent?.date || now,
    reactionCounts: {},
    commentCount: 0,
    autoGenerated: true
  };
}

function teamToFeedItem(team: ParentHomeTeam, authorId: string, authorName: string, now: Date): SocialFeedItem {
  return {
    id: `derived:team:${team.teamId}`,
    type: 'team_media',
    visibility: 'team',
    authorId,
    authorName,
    teamId: team.teamId,
    teamName: team.teamName,
    playerIds: team.players.map((player) => player.playerId),
    playerNames: team.players.map((player) => player.playerName),
    sourceType: 'team',
    sourceId: team.teamId,
    title: `${team.teamName} team update`,
    detail: team.nextEvent ? `${getScheduleTitle(team.nextEvent)} · ${formatEventDateLabel(team.nextEvent.date)}` : `${team.role}${team.sport ? ` · ${team.sport}` : ''}`,
    caption: team.unreadCount ? `${team.unreadCount} unread team message${team.unreadCount === 1 ? '' : 's'}.` : 'Team hub is ready.',
    media: team.photoUrl ? [{ type: 'image', url: team.photoUrl, name: `${team.teamName} photo` }] : [],
    route: `/teams?selectedTeamId=${encodeURIComponent(team.teamId)}&from=home`,
    createdAt: team.nextEvent?.date || now,
    reactionCounts: {},
    commentCount: 0,
    autoGenerated: true
  };
}
