import {
  addDoc,
  collection,
  db,
  doc,
  getDoc,
  getDocs,
  limit,
  query,
  serverTimestamp,
  setDoc,
  Timestamp,
  updateDoc,
  where
} from './adapters/legacySocialDb';
import { loadParentHome } from './homeService';
import { createLogger } from './logger';
import type { ParentHomeModel } from './homeLogic';
import { uploadTeamChatAttachment } from './chatService';
import type { AuthUser } from './types';
import {
  buildDerivedSocialFeedItems,
  buildFriendshipId,
  buildSocialHomeModel,
  emptySocialHome,
  mergeSocialFeedItems,
  normalizeSocialFriend,
  toSocialDate,
  type SocialFeedItem,
  type SocialFriend,
  type SocialHomeModel,
  type SocialMedia,
  type SocialPostType,
  type SocialVisibility
} from './socialLogic';

const primaryDataTimeoutMs = 5000;
const socialPostLimit = 30;
const friendSuggestionLimit = 8;
const publicUserProfileCollection = 'publicUserProfiles';
const logger = createLogger('social-service');

type FirestoreDoc = Record<string, any> & { id: string };

export type CreateSocialPostInput = {
  type: SocialPostType;
  visibility: SocialVisibility;
  title: string;
  detail?: string;
  caption?: string;
  teamId?: string | null;
  teamName?: string | null;
  playerIds?: string[];
  playerNames?: string[];
  sourceType?: string | null;
  sourceId?: string | null;
  route?: string | null;
  href?: string | null;
  media?: SocialMedia[];
  visibleUserIds?: string[];
};

function withTimeout<T>(promise: Promise<T>, label: string, timeoutMs = primaryDataTimeoutMs): Promise<T> {
  let timeoutId: number | undefined;
  const timeout = new Promise<T>((_, reject) => {
    timeoutId = window.setTimeout(() => reject(new Error(`${label} timed out.`)), timeoutMs);
  });
  return Promise.race([promise, timeout]).finally(() => {
    if (timeoutId) window.clearTimeout(timeoutId);
  });
}

function snapshotToDocs(snapshot: any): FirestoreDoc[] {
  return snapshot.docs.map((entry: any) => ({
    id: entry.id,
    ...entry.data()
  }));
}

function compactString(value: unknown) {
  return String(value || '').trim();
}

function normalizeEmail(value: unknown) {
  return compactString(value).toLowerCase();
}

async function hashSocialEmail(value: unknown) {
  const normalized = normalizeEmail(value);
  if (!normalized || !globalThis.crypto?.subtle) {
    return null;
  }
  const bytes = new TextEncoder().encode(normalized);
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((entry) => entry.toString(16).padStart(2, '0'))
    .join('');
}

function uniqueStrings(values: unknown[] = []) {
  return Array.from(new Set(values.map((value) => compactString(value)).filter(Boolean)));
}

function getUserDisplayName(user: AuthUser | null, fallback = 'ALL PLAYS user') {
  return compactString(user?.displayName) || compactString(user?.email) || fallback;
}

function mapSocialPost(docData: FirestoreDoc): SocialFeedItem {
  const snapshot = docData.snapshot && typeof docData.snapshot === 'object' ? docData.snapshot : {};
  const type = compactString(docData.type || snapshot.type || 'manual_post') as SocialPostType;
  const visibility = compactString(docData.visibility || 'team') as SocialVisibility;
  return {
    id: docData.id,
    type,
    visibility,
    authorId: compactString(docData.authorId),
    authorName: compactString(docData.authorName) || 'ALL PLAYS user',
    authorPhotoUrl: docData.authorPhotoUrl || null,
    teamId: docData.teamId || snapshot.teamId || null,
    teamName: docData.teamName || snapshot.teamName || null,
    playerIds: uniqueStrings(docData.playerIds || snapshot.playerIds || []),
    playerNames: uniqueStrings(docData.playerNames || snapshot.playerNames || []),
    sourceType: docData.sourceType || snapshot.sourceType || null,
    sourceId: docData.sourceId || snapshot.sourceId || null,
    title: compactString(docData.title || snapshot.title) || 'ALL PLAYS post',
    detail: compactString(docData.detail || snapshot.detail),
    caption: compactString(docData.caption) || null,
    media: Array.isArray(docData.media) ? docData.media.filter((entry: any) => entry?.url) : [],
    route: docData.route || snapshot.route || null,
    href: docData.href || snapshot.href || null,
    createdAt: toSocialDate(docData.createdAt),
    reactionCounts: docData.reactionCounts && typeof docData.reactionCounts === 'object' ? docData.reactionCounts : {},
    commentCount: Number(docData.commentCount || 0),
    hidden: docData.hidden === true,
    autoGenerated: docData.autoGenerated === true
  };
}

function getHomeTeamIds(home: ParentHomeModel) {
  return uniqueStrings((home.teams || []).map((team) => team.teamId));
}

function getHomeTeamNames(home: ParentHomeModel) {
  return (home.teams || []).reduce<Record<string, string>>((acc, team) => {
    if (team.teamId) acc[team.teamId] = team.teamName || team.teamId;
    return acc;
  }, {});
}

export async function loadSocialHome(user: AuthUser | null, homeOverride?: ParentHomeModel): Promise<SocialHomeModel> {
  if (!user?.uid) return emptySocialHome();
  const home = homeOverride || await loadParentHome(user);
  const authorName = getUserDisplayName(user);
  const derivedFeed = buildDerivedSocialFeedItems(home, user.uid, authorName);
  let friendshipsError: string | null = null;
  const [posts, friendships, suggestions] = await Promise.all([
    loadVisibleSocialPosts(user, home).catch((error) => {
      logger.warn('Unable to load social posts.', { error });
      return [];
    }),
    loadFriendships(user).catch((error) => {
      logger.warn('Unable to load friendships.', { error });
      // Surface this instead of silently rendering "no requests" — a swallowed
      // failure here hides incoming friend requests entirely (#3867).
      friendshipsError = error?.message || 'Unable to load friend requests.';
      return [];
    }),
    loadFriendSuggestions(user, home).catch((error) => {
      logger.warn('Unable to load friend suggestions.', { error });
      return [];
    })
  ]);

  return buildSocialHomeModel({
    feedItems: mergeSocialFeedItems(posts, derivedFeed),
    friendshipFriends: friendships,
    suggestions,
    currentUserId: user.uid,
    friendshipsError
  });
}

export async function loadVisibleSocialPosts(user: AuthUser, home: ParentHomeModel): Promise<SocialFeedItem[]> {
  const postDocs = new Map<string, FirestoreDoc>();
  const visibleQuery = query(
    collection(db, 'socialPosts'),
    where('visibleUserIds', 'array-contains', user.uid),
    limit(socialPostLimit)
  );
  const visibleSnapshot = await withTimeout(getDocs(visibleQuery), 'Social feed');
  snapshotToDocs(visibleSnapshot).forEach((post) => postDocs.set(post.id, post));

  for (const teamId of getHomeTeamIds(home).slice(0, 8)) {
    const teamQuery = query(
      collection(db, 'socialPosts'),
      where('teamIds', 'array-contains', teamId),
      limit(12)
    );
    const teamSnapshot = await withTimeout(getDocs(teamQuery), `Team social feed ${teamId}`).catch(() => null);
    if (teamSnapshot) snapshotToDocs(teamSnapshot).forEach((post) => postDocs.set(post.id, post));
  }

  return [...postDocs.values()]
    .map(mapSocialPost)
    .filter((post) => !post.hidden)
    .slice(0, socialPostLimit);
}

export async function loadFriendships(user: AuthUser): Promise<SocialFriend[]> {
  if (!user?.uid) return [];
  const friendshipQuery = query(
    collection(db, 'friendships'),
    where('memberIds', 'array-contains', user.uid),
    limit(50)
  );
  const snapshot = await withTimeout(getDocs(friendshipQuery), 'Friendships');
  const friendships = snapshotToDocs(snapshot);
  const friendDocs = await Promise.all(friendships.map(async (friendship) => {
    const otherUserId = (friendship.memberIds || []).find((id: string) => id !== user.uid);
    if (!otherUserId) return null;
    const userSnap = await getDoc(doc(db, publicUserProfileCollection, otherUserId)).catch(() => null);
    const userData = userSnap?.exists?.() ? { id: userSnap.id, ...userSnap.data() } : { id: otherUserId };
    return normalizeSocialFriend({
      ...userData,
      sharedTeamIds: friendship.sharedTeamIds || [],
      sharedTeamNames: friendship.sharedTeamNames || []
    }, user.uid, friendship);
  }));
  return friendDocs.filter(Boolean) as SocialFriend[];
}

export async function loadFriendSuggestions(user: AuthUser, home: ParentHomeModel): Promise<SocialFriend[]> {
  const teamIds = getHomeTeamIds(home);
  const teamNames = getHomeTeamNames(home);
  const suggestionsById = new Map<string, SocialFriend>();
  for (const teamId of teamIds.slice(0, 5)) {
    const teamUserQuery = query(
      collection(db, publicUserProfileCollection),
      where('discoveryTeamIds', 'array-contains', teamId),
      limit(12)
    );
    const snapshot = await withTimeout(getDocs(teamUserQuery), `Friend suggestions ${teamId}`).catch(() => null);
    if (!snapshot) continue;
    snapshotToDocs(snapshot).forEach((candidate) => {
      const friend = normalizeSocialFriend({
        ...candidate,
        sharedTeamIds: [teamId],
        sharedTeamNames: [teamNames[teamId] || teamId]
      }, user.uid);
      if (friend && friend.status === 'none') suggestionsById.set(friend.userId, friend);
    });
  }
  return [...suggestionsById.values()].slice(0, friendSuggestionLimit);
}

export async function searchSocialUsers(user: AuthUser | null, queryText: string, home: ParentHomeModel): Promise<SocialFriend[]> {
  if (!user?.uid) return [];
  const normalized = compactString(queryText);
  if (normalized.length < 2) return [];
  const lower = normalizeEmail(normalized);
  const resultsById = new Map<string, SocialFriend>();
  const teamNames = getHomeTeamNames(home);

  if (lower.includes('@')) {
    const emailHash = await hashSocialEmail(lower);
    if (emailHash) {
      const teamIds = getHomeTeamIds(home).slice(0, 10);
      for (const teamId of teamIds) {
        const emailSnapshot = await withTimeout(getDocs(query(
          collection(db, publicUserProfileCollection),
          where('emailHash', '==', emailHash),
          where('discoveryTeamIds', 'array-contains', teamId),
          limit(5)
        )), `Friend email search ${teamId}`).catch(() => null);
        if (emailSnapshot) {
          snapshotToDocs(emailSnapshot).forEach((candidate) => {
            const sharedTeamIds = uniqueStrings((candidate.discoveryTeamIds || []).filter((candidateTeamId: string) => teamNames[candidateTeamId]));
            const friend = normalizeSocialFriend({
              ...candidate,
              sharedTeamIds,
              sharedTeamNames: sharedTeamIds.map((sharedTeamId) => teamNames[sharedTeamId] || sharedTeamId)
            }, user.uid);
            if (friend) resultsById.set(friend.userId, friend);
          });
        }
      }
    }
  }

  const suggestions = await loadFriendSuggestions(user, home).catch(() => []);
  suggestions
    .filter((friend) => `${friend.name} ${friend.email || ''} ${friend.sharedTeamNames.join(' ')}`.toLowerCase().includes(lower))
    .forEach((friend) => resultsById.set(friend.userId, friend));

  return [...resultsById.values()].slice(0, 20);
}

export async function sendFriendRequest(user: AuthUser, friend: SocialFriend) {
  const friendshipId = buildFriendshipId(user.uid, friend.userId);
  if (!friendshipId) throw new Error('Friend request is missing a user.');
  await setDoc(doc(db, 'friendships', friendshipId), {
    requesterId: user.uid,
    recipientId: friend.userId,
    memberIds: [user.uid, friend.userId].sort(),
    status: 'pending',
    sharedTeamIds: friend.sharedTeamIds || [],
    sharedTeamNames: friend.sharedTeamNames || [],
    blockedBy: [],
    // Re-requesting after a prior decline/remove: reset the response so the
    // recipient sees a fresh pending request rather than stale state (#3867).
    respondedAt: null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  }, { merge: true });
  return friendshipId;
}

export async function respondToFriendRequest(friendshipId: string, status: 'accepted' | 'declined') {
  await updateDoc(doc(db, 'friendships', friendshipId), {
    status,
    respondedAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
}

export async function removeFriend(friendshipId: string) {
  await updateDoc(doc(db, 'friendships', friendshipId), {
    status: 'removed',
    updatedAt: serverTimestamp()
  });
}

export async function blockFriend(friendshipId: string, userId: string) {
  await updateDoc(doc(db, 'friendships', friendshipId), {
    status: 'blocked',
    blockedBy: [userId],
    updatedAt: serverTimestamp()
  });
}

export async function createSocialPost(user: AuthUser, input: CreateSocialPostInput) {
  const title = compactString(input.title);
  if (!title) throw new Error('Add a title before posting.');
  const visibility = input.visibility || 'team';
  const teamIds = uniqueStrings([input.teamId || '']);
  const visibleUserIds = uniqueStrings([user.uid, ...(input.visibleUserIds || [])]);
  const playerIds = uniqueStrings(input.playerIds || []);
  const playerNames = uniqueStrings(input.playerNames || []);
  const createdAt = Timestamp.now();
  const snapshot = {
    type: input.type,
    title,
    detail: input.detail || '',
    teamId: input.teamId || null,
    teamName: input.teamName || null,
    playerIds,
    playerNames,
    sourceType: input.sourceType || null,
    sourceId: input.sourceId || null,
    route: input.route || null,
    href: input.href || null
  };

  const postRef = await addDoc(collection(db, 'socialPosts'), {
    type: input.type,
    visibility,
    authorId: user.uid,
    authorName: getUserDisplayName(user),
    authorEmail: user.email || null,
    authorPhotoUrl: user.photoUrl || null,
    teamId: input.teamId || null,
    teamName: input.teamName || null,
    teamIds,
    playerIds,
    playerNames,
    sourceType: input.sourceType || null,
    sourceId: input.sourceId || null,
    title,
    detail: input.detail || '',
    caption: input.caption || '',
    media: input.media || [],
    route: input.route || null,
    href: input.href || null,
    visibleUserIds,
    snapshot,
    hidden: false,
    reportCount: 0,
    reactionCounts: {},
    commentCount: 0,
    createdAt,
    updatedAt: createdAt
  });
  return postRef.id;
}

export async function uploadSocialPostMedia(teamId: string, file: File): Promise<SocialMedia> {
  if (!teamId) {
    throw new Error('Choose a team before adding media.');
  }
  const attachment = await uploadTeamChatAttachment(teamId, file);
  if (!attachment.url) {
    throw new Error('Media upload did not return a usable URL.');
  }
  return {
    type: attachment.type,
    url: attachment.url,
    name: attachment.name || file.name || null,
    thumbnailUrl: attachment.thumbnailUrl || null
  };
}

export async function reactToSocialPost(postId: string, user: AuthUser, reactionKey = 'like') {
  await setDoc(doc(db, 'socialPosts', postId, 'reactions', user.uid), {
    userId: user.uid,
    reactionKey,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  }, { merge: true });
}

export async function commentOnSocialPost(postId: string, user: AuthUser, text: string) {
  const trimmed = compactString(text);
  if (!trimmed) throw new Error('Write a comment first.');
  await addDoc(collection(db, 'socialPosts', postId, 'comments'), {
    text: trimmed,
    authorId: user.uid,
    authorName: getUserDisplayName(user),
    authorPhotoUrl: user.photoUrl || null,
    hidden: false,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
}

export async function reportSocialPost(postId: string, user: AuthUser, reason = 'Reported from app') {
  await addDoc(collection(db, 'socialReports'), {
    postId,
    reporterId: user.uid,
    reason,
    status: 'open',
    createdAt: serverTimestamp()
  });
}

export async function hideSocialPost(postId: string, user: AuthUser) {
  await updateDoc(doc(db, 'socialPosts', postId), {
    hidden: true,
    hiddenBy: user.uid,
    hiddenAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
}
