import {
  addDoc,
  collection,
  db,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  runTransaction,
  serverTimestamp,
  setDoc,
  startAfter,
  Timestamp,
  updateDoc,
  where
} from './adapters/legacySocialDb';
import { loadParentHome } from './homeService';
import { createLogger } from './logger';
import { toAppServiceError } from './appErrors';
import type { ParentHomeModel } from './homeLogic';
import { uploadTeamChatAttachment } from './chatService';
import type { AuthUser } from './types';
import {
  buildFriendshipId,
  buildSocialHomeModel,
  emptySocialHome,
  normalizeSocialFriend,
  sortSocialFeedItems,
  toSocialDate,
  type SocialFeedItem,
  type SocialFriend,
  type SocialHomeModel,
  type SocialMedia,
  type SocialPostType,
  type SocialVisibility
} from './socialLogic';

const primaryDataTimeoutMs = 5000;
const socialPostLimit = 30;
const hiddenSocialPostPageSize = 200;
const teamSocialPostLimit = 12;
const friendSuggestionLimit = 8;
const publicUserProfileCollection = 'publicUserProfiles';
const logger = createLogger('social-service');

type FirestoreDoc = Record<string, any> & { id: string };

export type CreateSocialPostInput = {
  type: SocialPostType;
  visibility: SocialVisibility;
  title: string;
  detail?: string;
  caption?: string;
  teamId?: string | null;
  teamName?: string | null;
  playerIds?: string[];
  playerNames?: string[];
  sourceType?: string | null;
  sourceId?: string | null;
  route?: string | null;
  href?: string | null;
  media?: SocialMedia[];
  visibleUserIds?: string[];
};

export type FriendProfileModel = {
  userId: string;
  name: string;
  photoUrl: string | null;
  sharedTeamNames: string[];
  isSelf: boolean;
  posts: SocialFeedItem[];
};

function withTimeout<T>(promise: Promise<T>, label: string, timeoutMs = primaryDataTimeoutMs): Promise<T> {
  let timeoutId: number | undefined;
  const timeout = new Promise<T>((_, reject) => {
    timeoutId = window.setTimeout(() => reject(new Error(`${label} timed out.`)), timeoutMs);
  });
  return Promise.race([promise, timeout]).finally(() => {
    if (timeoutId) window.clearTimeout(timeoutId);
  });
}

function snapshotToDocs(snapshot: any): FirestoreDoc[] {
  return snapshot.docs.map((entry: any) => ({
    id: entry.id,
    ...entry.data()
  }));
}

function compactString(value: unknown) {
  return String(value || '').trim();
}

function normalizeEmail(value: unknown) {
  return compactString(value).toLowerCase();
}

async function hashSocialEmail(value: unknown) {
  const normalized = normalizeEmail(value);
  if (!normalized || !globalThis.crypto?.subtle) {
    return null;
  }
  const bytes = new TextEncoder().encode(normalized);
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((entry) => entry.toString(16).padStart(2, '0'))
    .join('');
}

function uniqueStrings(values: unknown[] = []) {
  return Array.from(new Set(values.map((value) => compactString(value)).filter(Boolean)));
}

function getUserDisplayName(user: AuthUser | null, fallback = 'ALL PLAYS user') {
  return compactString(user?.displayName) || compactString(user?.email) || fallback;
}

function mapSocialPost(docData: FirestoreDoc): SocialFeedItem {
  const snapshot = docData.snapshot && typeof docData.snapshot === 'object' ? docData.snapshot : {};
  const type = compactString(docData.type || snapshot.type || 'manual_post') as SocialPostType;
  const visibility = compactString(docData.visibility || 'team') as SocialVisibility;
  return {
    id: docData.id,
    type,
    visibility,
    authorId: compactString(docData.authorId),
    authorName: compactString(docData.authorName) || 'ALL PLAYS user',
    authorPhotoUrl: docData.authorPhotoUrl || null,
    teamId: docData.teamId || snapshot.teamId || null,
    teamName: docData.teamName || snapshot.teamName || null,
    playerIds: uniqueStrings(docData.playerIds || snapshot.playerIds || []),
    playerNames: uniqueStrings(docData.playerNames || snapshot.playerNames || []),
    sourceType: docData.sourceType || snapshot.sourceType || null,
    sourceId: docData.sourceId || snapshot.sourceId || null,
    title: compactString(docData.title || snapshot.title) || 'ALL PLAYS post',
    detail: compactString(docData.detail || snapshot.detail),
    caption: compactString(docData.caption) || null,
    media: Array.isArray(docData.media) ? docData.media.filter((entry: any) => entry?.url) : [],
    route: docData.route || snapshot.route || null,
    href: docData.href || snapshot.href || null,
    createdAt: toSocialDate(docData.createdAt),
    reactionCounts: docData.reactionCounts && typeof docData.reactionCounts === 'object' ? docData.reactionCounts : {},
    commentCount: Number(docData.commentCount || 0),
    viewerHasLiked: docData.viewerHasLiked === true,
    hidden: docData.hidden === true,
    autoGenerated: docData.autoGenerated === true
  };
}

function isAcceptedFriendship(friendship: FirestoreDoc, viewerId: string, profileUserId: string) {
  const memberIds = uniqueStrings(friendship.memberIds || []);
  return friendship.status === 'accepted' &&
    memberIds.length === 2 &&
    memberIds.includes(viewerId) &&
    memberIds.includes(profileUserId);
}

function getHomeTeamIds(home: ParentHomeModel) {
  return uniqueStrings((home.teams || []).map((team) => team.teamId));
}

function getHomeTeamNames(home: ParentHomeModel) {
  return (home.teams || []).reduce<Record<string, string>>((acc, team) => {
    if (team.teamId) acc[team.teamId] = team.teamName || team.teamId;
    return acc;
  }, {});
}

export async function loadSocialHome(user: AuthUser | null, homeOverride?: ParentHomeModel): Promise<SocialHomeModel> {
  if (!user?.uid) return emptySocialHome();
  const home = homeOverride || await loadParentHome(user);
  let friendshipsError: string | null = null;
  const [posts, friendships, suggestions] = await Promise.all([
    loadVisibleSocialPosts(user, home).catch((error) => {
      logger.warn('Unable to load social posts.', { error });
      return [];
    }),
    loadFriendships(user).catch((error) => {
      const appError = toAppServiceError(error, "Couldn't load friend requests.");
      logger.warn('Unable to load friendships.', { error: appError });
      // Surface this instead of silently rendering "no requests" — a swallowed
      // failure here hides incoming friend requests entirely (#3867).
      friendshipsError = appError.message;
      return [];
    }),
    loadFriendSuggestions(user, home).catch((error) => {
      logger.warn('Unable to load friend suggestions.', { error });
      return [];
    })
  ]);

  return buildSocialHomeModel({
    feedItems: posts,
    friendshipFriends: friendships,
    suggestions,
    currentUserId: user.uid,
    friendshipsError
  });
}

export async function loadVisibleSocialPosts(user: AuthUser, home: ParentHomeModel): Promise<SocialFeedItem[]> {
  const hiddenPostIds = await loadHiddenSocialPostIds(user.uid);
  const postDocs = new Map<string, FirestoreDoc>();
  const [visiblePosts, teamPostSnapshots] = await Promise.all([
    loadSocialPostQueryPages({
      buildQuery: (cursor) => query(
        collection(db, 'socialPosts'),
        where('visibleUserIds', 'array-contains', user.uid),
        orderBy('createdAt', 'desc'),
        ...(cursor ? [startAfter(cursor)] : []),
        limit(socialPostLimit)
      ),
      label: 'Social feed',
      hiddenPostIds,
      pageSize: socialPostLimit,
      visibleLimit: socialPostLimit
    }),
    Promise.all(getHomeTeamIds(home).slice(0, 8).map((teamId) => loadSocialPostQueryPages({
      buildQuery: (cursor) => query(
        collection(db, 'socialPosts'),
        where('teamIds', 'array-contains', teamId),
        orderBy('createdAt', 'desc'),
        ...(cursor ? [startAfter(cursor)] : []),
        limit(teamSocialPostLimit)
      ),
      label: `Team social feed ${teamId}`,
      hiddenPostIds,
      pageSize: teamSocialPostLimit,
      visibleLimit: teamSocialPostLimit
    }).catch(() => [])))
  ]);
  visiblePosts.forEach((post) => postDocs.set(post.id, post));
  teamPostSnapshots.flat().forEach((post) => postDocs.set(post.id, post));

  const posts = sortSocialFeedItems([...postDocs.values()]
    .map(mapSocialPost)
    .filter((post) => !post.hidden && !hiddenPostIds.has(post.id)))
    .slice(0, socialPostLimit);
  const viewerReactions = await loadViewerSocialPostReactions(posts, user.uid);
  return posts.map((post) => ({ ...post, viewerHasLiked: viewerReactions.has(post.id) }));
}

async function loadSocialPostQueryPages({
  buildQuery,
  label,
  hiddenPostIds,
  pageSize,
  visibleLimit
}: {
  buildQuery: (cursor: any | null) => any;
  label: string;
  hiddenPostIds: Set<string>;
  pageSize: number;
  visibleLimit: number;
}) {
  const visiblePosts: FirestoreDoc[] = [];
  let cursor: any | null = null;
  let previousCursorId = '';
  while (visiblePosts.length < visibleLimit) {
    const snapshot = await withTimeout(getDocs(buildQuery(cursor)), label);
    const snapshotDocs = Array.isArray(snapshot?.docs) ? snapshot.docs : [];
    snapshotToDocs(snapshot).forEach((post) => {
      if (!post.hidden && !hiddenPostIds.has(post.id) && visiblePosts.length < visibleLimit) {
        visiblePosts.push(post);
      }
    });
    if (snapshotDocs.length < pageSize || visiblePosts.length >= visibleLimit) break;
    const nextCursor = snapshotDocs[snapshotDocs.length - 1];
    if (!nextCursor?.id || nextCursor.id === previousCursorId) break;
    cursor = nextCursor;
    previousCursorId = nextCursor.id;
  }
  return visiblePosts;
}

async function loadHiddenSocialPostIds(userId: string) {
  const hiddenPostIds = new Set<string>();
  let cursor: any | null = null;
  let previousCursorId = '';
  while (true) {
    const snapshot = await withTimeout(getDocs(query(
      collection(db, 'users', userId, 'hiddenSocialPosts'),
      ...(cursor ? [startAfter(cursor)] : []),
      limit(hiddenSocialPostPageSize)
    )), 'Hidden social posts').catch(() => null);
    if (!snapshot) break;
    const snapshotDocs = Array.isArray(snapshot.docs) ? snapshot.docs : [];
    snapshotToDocs(snapshot).forEach((entry) => hiddenPostIds.add(entry.id));
    if (snapshotDocs.length < hiddenSocialPostPageSize) break;
    const nextCursor = snapshotDocs[snapshotDocs.length - 1];
    if (!nextCursor?.id || nextCursor.id === previousCursorId) break;
    cursor = nextCursor;
    previousCursorId = nextCursor.id;
  }
  return hiddenPostIds;
}

async function loadViewerSocialPostReactions(posts: SocialFeedItem[], userId: string) {
  const reactionStates = await Promise.all(posts.map(async (post) => {
    const reactionSnap = await getDoc(doc(db, 'socialPosts', post.id, 'reactions', userId)).catch(() => null);
    return reactionSnap?.exists?.() ? post.id : null;
  }));
  return new Set(reactionStates.filter((postId): postId is string => Boolean(postId)));
}

export async function loadFriendProfile(user: AuthUser, profileUserId: string): Promise<FriendProfileModel> {
  const viewerId = compactString(user?.uid);
  const targetUserId = compactString(profileUserId);
  if (!viewerId || !targetUserId) {
    throw new Error('This profile is unavailable.');
  }

  const isSelf = viewerId === targetUserId;
  let friendship: FirestoreDoc | null = null;
  if (!isSelf) {
    const friendshipId = buildFriendshipId(viewerId, targetUserId);
    const friendshipSnap = await withTimeout(
      getDoc(doc(db, 'friendships', friendshipId)),
      'Friend profile access'
    );
    friendship = friendshipSnap?.exists?.()
      ? { id: friendshipSnap.id || friendshipId, ...friendshipSnap.data() }
      : null;
    if (!friendship || !isAcceptedFriendship(friendship, viewerId, targetUserId)) {
      throw new Error('This profile is available to accepted friends only.');
    }
  }

  const [profileSnap, hiddenPostIds] = await Promise.all([
    withTimeout(getDoc(doc(db, publicUserProfileCollection, targetUserId)), 'Friend profile'),
    loadHiddenSocialPostIds(viewerId)
  ]);
  const postDocs = await loadSocialPostQueryPages({
    buildQuery: (cursor) => query(
      collection(db, 'socialPosts'),
      where('visibleUserIds', 'array-contains', viewerId),
      where('authorId', '==', targetUserId),
      where('hidden', '==', false),
      orderBy('createdAt', 'desc'),
      ...(cursor ? [startAfter(cursor)] : []),
      limit(socialPostLimit)
    ),
    label: 'Friend profile posts',
    hiddenPostIds,
    pageSize: socialPostLimit,
    visibleLimit: socialPostLimit
  });
  const profile = profileSnap?.exists?.() ? profileSnap.data() || {} : {};
  const posts = sortSocialFeedItems(postDocs
    .map(mapSocialPost)
    .filter((post) => !post.hidden && !hiddenPostIds.has(post.id)));
  const viewerReactions = await loadViewerSocialPostReactions(posts, viewerId);
  const hydratedPosts = posts.map((post) => ({
    ...post,
    viewerHasLiked: viewerReactions.has(post.id)
  }));

  return {
    userId: targetUserId,
    name: compactString(profile.displayName || profile.fullName) || hydratedPosts[0]?.authorName || 'ALL PLAYS member',
    photoUrl: compactString(profile.photoUrl) || null,
    sharedTeamNames: isSelf ? [] : uniqueStrings(friendship?.sharedTeamNames || []),
    isSelf,
    posts: hydratedPosts
  };
}

export async function loadFriendships(user: AuthUser): Promise<SocialFriend[]> {
  if (!user?.uid) return [];
  const requestedFriendshipsQuery = query(
    collection(db, 'friendships'),
    where('requesterId', '==', user.uid),
    limit(50)
  );
  const receivedFriendshipsQuery = query(
    collection(db, 'friendships'),
    where('recipientId', '==', user.uid),
    limit(50)
  );
  const snapshots = await withTimeout(Promise.all([
    getDocs(requestedFriendshipsQuery),
    getDocs(receivedFriendshipsQuery)
  ]), 'Friendships');
  const friendshipDocs = new Map<string, FirestoreDoc>();
  snapshots.forEach((snapshot) => {
    snapshotToDocs(snapshot).forEach((friendship) => friendshipDocs.set(friendship.id, friendship));
  });
  // Keep both bounded result sets. Applying a second global limit here could
  // hide incoming requests whenever a user already has 50 outgoing records.
  const friendships = [...friendshipDocs.values()];
  const friendDocs = await Promise.all(friendships.map(async (friendship) => {
    const otherUserId = (friendship.memberIds || []).find((id: string) => id !== user.uid);
    if (!otherUserId) return null;
    const userSnap = await getDoc(doc(db, publicUserProfileCollection, otherUserId)).catch(() => null);
    const userData = userSnap?.exists?.() ? { id: userSnap.id, ...userSnap.data() } : { id: otherUserId };
    return normalizeSocialFriend({
      ...userData,
      sharedTeamIds: friendship.sharedTeamIds || [],
      sharedTeamNames: friendship.sharedTeamNames || []
    }, user.uid, friendship);
  }));
  return friendDocs.filter(Boolean) as SocialFriend[];
}

export async function loadFriendSuggestions(user: AuthUser, home: ParentHomeModel): Promise<SocialFriend[]> {
  const teamIds = getHomeTeamIds(home);
  const teamNames = getHomeTeamNames(home);
  const suggestionsById = new Map<string, SocialFriend>();
  for (const teamId of teamIds.slice(0, 5)) {
    const teamUserQuery = query(
      collection(db, publicUserProfileCollection),
      where('discoveryTeamIds', 'array-contains', teamId),
      limit(12)
    );
    const snapshot = await withTimeout(getDocs(teamUserQuery), `Friend suggestions ${teamId}`).catch(() => null);
    if (!snapshot) continue;
    snapshotToDocs(snapshot).forEach((candidate) => {
      const friend = normalizeSocialFriend({
        ...candidate,
        sharedTeamIds: [teamId],
        sharedTeamNames: [teamNames[teamId] || teamId]
      }, user.uid);
      if (friend && friend.status === 'none') suggestionsById.set(friend.userId, friend);
    });
  }
  return [...suggestionsById.values()].slice(0, friendSuggestionLimit);
}

export async function searchSocialUsers(user: AuthUser | null, queryText: string, home: ParentHomeModel): Promise<SocialFriend[]> {
  if (!user?.uid) return [];
  const normalized = compactString(queryText);
  if (normalized.length < 2) return [];
  const lower = normalizeEmail(normalized);
  const resultsById = new Map<string, SocialFriend>();
  const teamNames = getHomeTeamNames(home);

  if (lower.includes('@')) {
    const emailHash = await hashSocialEmail(lower);
    if (emailHash) {
      const teamIds = getHomeTeamIds(home).slice(0, 10);
      for (const teamId of teamIds) {
        const emailSnapshot = await withTimeout(getDocs(query(
          collection(db, publicUserProfileCollection),
          where('emailHash', '==', emailHash),
          where('discoveryTeamIds', 'array-contains', teamId),
          limit(5)
        )), `Friend email search ${teamId}`).catch(() => null);
        if (emailSnapshot) {
          snapshotToDocs(emailSnapshot).forEach((candidate) => {
            const sharedTeamIds = uniqueStrings((candidate.discoveryTeamIds || []).filter((candidateTeamId: string) => teamNames[candidateTeamId]));
            const friend = normalizeSocialFriend({
              ...candidate,
              sharedTeamIds,
              sharedTeamNames: sharedTeamIds.map((sharedTeamId) => teamNames[sharedTeamId] || sharedTeamId)
            }, user.uid);
            if (friend) resultsById.set(friend.userId, friend);
          });
        }
      }
    }
  }

  const suggestions = await loadFriendSuggestions(user, home).catch(() => []);
  suggestions
    .filter((friend) => `${friend.name} ${friend.email || ''} ${friend.sharedTeamNames.join(' ')}`.toLowerCase().includes(lower))
    .forEach((friend) => resultsById.set(friend.userId, friend));

  return [...resultsById.values()].slice(0, 20);
}

export async function sendFriendRequest(user: AuthUser, friend: SocialFriend) {
  const friendshipId = buildFriendshipId(user.uid, friend.userId);
  if (!friendshipId) throw new Error('Friend request is missing a user.');
  await setDoc(doc(db, 'friendships', friendshipId), {
    requesterId: user.uid,
    recipientId: friend.userId,
    memberIds: [user.uid, friend.userId].sort(),
    status: 'pending',
    sharedTeamIds: friend.sharedTeamIds || [],
    sharedTeamNames: friend.sharedTeamNames || [],
    blockedBy: [],
    // Re-requesting after a prior decline/remove: reset the response so the
    // recipient sees a fresh pending request rather than stale state (#3867).
    respondedAt: null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  }, { merge: true });
  return friendshipId;
}

export async function respondToFriendRequest(friendshipId: string, status: 'accepted' | 'declined') {
  await updateDoc(doc(db, 'friendships', friendshipId), {
    status,
    respondedAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
}

export async function removeFriend(friendshipId: string) {
  await updateDoc(doc(db, 'friendships', friendshipId), {
    status: 'removed',
    updatedAt: serverTimestamp()
  });
}

export async function blockFriend(friendshipId: string, userId: string) {
  await updateDoc(doc(db, 'friendships', friendshipId), {
    status: 'blocked',
    blockedBy: [userId],
    updatedAt: serverTimestamp()
  });
}

export async function createSocialPost(user: AuthUser, input: CreateSocialPostInput) {
  const title = compactString(input.title);
  if (!title) throw new Error('Add a title before posting.');
  const visibility = input.visibility || 'team';
  const teamIds = uniqueStrings([input.teamId || '']);
  const visibleUserIds = uniqueStrings([user.uid, ...(input.visibleUserIds || [])]);
  const playerIds = uniqueStrings(input.playerIds || []);
  const playerNames = uniqueStrings(input.playerNames || []);
  const createdAt = Timestamp.now();
  const snapshot = {
    type: input.type,
    title,
    detail: input.detail || '',
    teamId: input.teamId || null,
    teamName: input.teamName || null,
    playerIds,
    playerNames,
    sourceType: input.sourceType || null,
    sourceId: input.sourceId || null,
    route: input.route || null,
    href: input.href || null
  };

  const postData = {
    type: input.type,
    visibility,
    authorId: user.uid,
    authorName: getUserDisplayName(user),
    authorEmail: user.email || null,
    authorPhotoUrl: user.photoUrl || null,
    teamId: input.teamId || null,
    teamName: input.teamName || null,
    teamIds,
    playerIds,
    playerNames,
    sourceType: input.sourceType || null,
    sourceId: input.sourceId || null,
    title,
    detail: input.detail || '',
    caption: input.caption || '',
    media: input.media || [],
    route: input.route || null,
    href: input.href || null,
    visibleUserIds,
    snapshot,
    hidden: false,
    reportCount: 0,
    reactionCounts: {},
    commentCount: 0,
    createdAt,
    updatedAt: createdAt
  };
  const postRef = await addDoc(collection(db, 'socialPosts'), postData);
  return mapSocialPost({ id: postRef.id, ...postData });
}

export async function uploadSocialPostMedia(teamId: string, file: File): Promise<SocialMedia> {
  if (!teamId) {
    throw new Error('Choose a team before adding media.');
  }
  const attachment = await uploadTeamChatAttachment(teamId, file);
  if (!attachment.url) {
    throw new Error('Media upload did not return a usable URL.');
  }
  return {
    type: attachment.type,
    url: attachment.url,
    name: attachment.name || file.name || null,
    thumbnailUrl: attachment.thumbnailUrl || null
  };
}

export async function reactToSocialPost(postId: string, user: AuthUser, reactionKey = 'like') {
  if (reactionKey !== 'like') {
    throw new Error('This reaction is not supported yet.');
  }
  const postRef = doc(db, 'socialPosts', postId);
  const reactionRef = doc(db, 'socialPosts', postId, 'reactions', user.uid);
  return runTransaction(db, async (transaction: any) => {
    const [postSnap, reactionSnap] = await Promise.all([
      transaction.get(postRef),
      transaction.get(reactionRef)
    ]);
    if (!postSnap.exists()) {
      throw new Error('This post is no longer available.');
    }
    const post = postSnap.data() || {};
    const currentCount = Math.max(0, Number(post.reactionCounts?.like || 0));
    const liked = !reactionSnap.exists();
    const count = liked ? currentCount + 1 : Math.max(0, currentCount - 1);

    if (liked) {
      transaction.set(reactionRef, {
        userId: user.uid,
        reactionKey,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });
    } else {
      transaction.delete(reactionRef);
    }
    transaction.update(postRef, {
      'reactionCounts.like': count,
      updatedAt: serverTimestamp()
    });
    return { liked, count };
  });
}

export async function commentOnSocialPost(postId: string, user: AuthUser, text: string) {
  const trimmed = compactString(text);
  if (!trimmed) throw new Error('Write a comment first.');
  await addDoc(collection(db, 'socialPosts', postId, 'comments'), {
    text: trimmed,
    authorId: user.uid,
    authorName: getUserDisplayName(user),
    authorPhotoUrl: user.photoUrl || null,
    hidden: false,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
}

export async function reportSocialPost(postId: string, user: AuthUser, reason = 'Reported from app') {
  await addDoc(collection(db, 'socialReports'), {
    postId,
    reporterId: user.uid,
    reason,
    status: 'open',
    createdAt: serverTimestamp()
  });
}

export async function hideSocialPost(postId: string, user: AuthUser) {
  await setDoc(doc(db, 'users', user.uid, 'hiddenSocialPosts', postId), {
    postId,
    hiddenAt: serverTimestamp()
  });
}
