import React from 'react';

function createIcon(name: string) {
  return function LucideIcon(props: Record<string, unknown>) {
    return React.createElement('svg', { ...props, 'data-icon': name });
  };
}

// Named exports for icons referenced by tests that use data-icon attribute assertions.
export const AlertCircle = createIcon('AlertCircle');
export const Archive = createIcon('Archive');
export const BarChart3 = createIcon('BarChart3');
export const Bell = createIcon('Bell');
export const BellOff = createIcon('BellOff');
export const Bot = createIcon('Bot');
export const CalendarDays = createIcon('CalendarDays');
export const CalendarPlus = createIcon('CalendarPlus');
export const Camera = createIcon('Camera');
export const Check = createIcon('Check');
export const Car = createIcon('Car');
export const ChevronDown = createIcon('ChevronDown');
export const ChevronLeft = createIcon('ChevronLeft');
export const ChevronRight = createIcon('ChevronRight');
export const ChevronUp = createIcon('ChevronUp');
export const CheckCircle2 = createIcon('CheckCircle2');
export const Clipboard = createIcon('Clipboard');
export const ClipboardCheck = createIcon('ClipboardCheck');
export const ClipboardList = createIcon('ClipboardList');
export const Clock = createIcon('Clock');
export const Copy = createIcon('Copy');
export const CreditCard = createIcon('CreditCard');
export const Download = createIcon('Download');
export const Dumbbell = createIcon('Dumbbell');
export const Edit3 = createIcon('Edit3');
export const ExternalLink = createIcon('ExternalLink');
export const FilePlus2 = createIcon('FilePlus2');
export const FileText = createIcon('FileText');
export const Filter = createIcon('Filter');
export const ImageIcon = createIcon('ImageIcon');
export const Images = createIcon('Images');
export const ImagePlus = createIcon('ImagePlus');
export const Home = createIcon('Home');
export const KeyRound = createIcon('KeyRound');
export const Link2 = createIcon('Link2');
export const Link = createIcon('Link');
export const ListChecks = createIcon('ListChecks');
export const Loader2 = createIcon('Loader2');
export const LogOut = createIcon('LogOut');
export const Mail = createIcon('Mail');
export const MapPin = createIcon('MapPin');
export const MessageCircle = createIcon('MessageCircle');
export const Mic = createIcon('Mic');
export const MoreVertical = createIcon('MoreVertical');
export const Newspaper = createIcon('Newspaper');
export const Paperclip = createIcon('Paperclip');
export const Plus = createIcon('Plus');
export const Radio = createIcon('Radio');
export const RefreshCw = createIcon('RefreshCw');
export const Save = createIcon('Save');
export const Search = createIcon('Search');
export const Send = createIcon('Send');
export const Settings = createIcon('Settings');
export const Share2 = createIcon('Share2');
export const Shield = createIcon('Shield');
export const ShieldCheck = createIcon('ShieldCheck');
export const SlidersHorizontal = createIcon('SlidersHorizontal');
export const Smile = createIcon('Smile');
export const Sparkles = createIcon('Sparkles');
export const Ticket = createIcon('Ticket');
export const Trash2 = createIcon('Trash2');
export const Upload = createIcon('Upload');
export const UserCircle = createIcon('UserCircle');
export const UserPlus = createIcon('UserPlus');
export const UserRound = createIcon('UserRound');
export const Users = createIcon('Users');
export const UsersRound = createIcon('UsersRound');
export const Video = createIcon('Video');
export const WalletCards = createIcon('WalletCards');
export const X = createIcon('X');
export const XCircle = createIcon('XCircle');
