/* Auto-generated typed adapter boundary for legacy js/ team-detail imports (#2066).
 * Bindings re-exported as-is so existing js/* test mocks apply via the @legacy alias. */
import { addPlayer as legacy_addPlayer, createConfig as legacy_createConfig, getAggregatedStatsForGames as legacy_getAggregatedStatsForGames, getAdSpaceSponsors as legacy_getAdSpaceSponsors, getConfigs as legacy_getConfigs, getGames as legacy_getGames, inviteParent as legacy_inviteParent, getLocalAttractionSponsors as legacy_getLocalAttractionSponsors, getPlayers as legacy_getPlayers, getPlayerTrackingStatuses as legacy_getPlayerTrackingStatuses, getPublicTrackingItems as legacy_getPublicTrackingItems, getRosterFieldDefinitions as legacy_getRosterFieldDefinitions, getTeam as legacy_getTeam, setTeamTrackingStatus as legacy_setTeamTrackingStatus, updateTeam as legacy_updateTeam, grantScorekeeperAccess as legacy_grantScorekeeperAccess, grantVideographerAccess as legacy_grantVideographerAccess, inviteAdmin as legacy_inviteAdmin, addTeamAdminEmail as legacy_addTeamAdminEmail, revokeScorekeeperAccess as legacy_revokeScorekeeperAccess, revokeVideographerAccess as legacy_revokeVideographerAccess, deactivatePlayer as legacy_deactivatePlayer, reactivatePlayer as legacy_reactivatePlayer, setPlayerPrivateRosterProfileFields as legacy_setPlayerPrivateRosterProfileFields, updateConfig as legacy_updateConfig, uploadPlayerPhoto as legacy_uploadPlayerPhoto, uploadTeamPhoto as legacy_uploadTeamPhoto } from '@legacy/db.js';
import { sendInviteEmail as legacy_sendInviteEmail } from '@legacy/auth.js';
import { inviteExistingTeamAdmin as legacy_inviteExistingTeamAdmin } from '@legacy/edit-team-admin-invites.js';
import { collection as legacy_collection, db as legacy_db, doc as legacy_doc, getDoc as legacy_getDoc, getDocs as legacy_getDocs, query as legacy_query, serverTimestamp as legacy_serverTimestamp, setDoc as legacy_setDoc, updateDoc as legacy_updateDoc, where as legacy_where } from '@legacy/firebase.js';
import { normalizeRosterFieldDefinitions as legacy_normalizeRosterFieldDefinitions, splitRosterProfileValuesByVisibility as legacy_splitRosterProfileValuesByVisibility, validateRosterProfileValues as legacy_validateRosterProfileValues } from '@legacy/roster-profile-fields.js';
import { describeScheduleReminderWindow as legacy_describeScheduleReminderWindow, normalizeScheduleNotificationSettings as legacy_normalizeScheduleNotificationSettings } from '@legacy/schedule-notifications.js';
import { calculateSeasonRecord as legacy_calculateSeasonRecord, listSeasonLabels as legacy_listSeasonLabels } from '@legacy/season-record.js';
import { computeNativeStandings as legacy_computeNativeStandings } from '@legacy/native-standings.js';
import { buildPlayerLeaderboardSnapshot as legacy_buildPlayerLeaderboardSnapshot, normalizeStatTrackerConfig as legacy_normalizeStatTrackerConfig, selectAnalyticsConfig as legacy_selectAnalyticsConfig } from '@legacy/stat-leaderboards.js';
import { getVisiblePlayerTrackingSummary as legacy_getVisiblePlayerTrackingSummary, normalizeTrackingStatus as legacy_normalizeTrackingStatus } from '@legacy/player-tracking-summary.js';
import { hasFullTeamAccess as legacy_hasFullTeamAccess, normalizeAdminEmailList as legacy_normalizeAdminEmailList } from '@legacy/team-access.js';
import { buildTeamStaffPermissionsViewModel as legacy_buildTeamStaffPermissionsViewModel } from '@legacy/team-staff-permissions.js';
import { buildTrackingStatusPayload as legacy_buildTrackingStatusPayload, summarizeTrackingStatus as legacy_summarizeTrackingStatus } from '@legacy/tracking-status-admin.js';

export const addPlayer = legacy_addPlayer as (...args: any[]) => any;
export const createConfig = legacy_createConfig as (...args: any[]) => any;
export const getAggregatedStatsForGames = legacy_getAggregatedStatsForGames as (...args: any[]) => any;
export const getAdSpaceSponsors = legacy_getAdSpaceSponsors as (...args: any[]) => any;
export const getConfigs = legacy_getConfigs as (...args: any[]) => any;
export const getGames = legacy_getGames as (...args: any[]) => any;
export const inviteParent = legacy_inviteParent as (...args: any[]) => any;
export const getLocalAttractionSponsors = legacy_getLocalAttractionSponsors as (...args: any[]) => any;
export const getPlayers = legacy_getPlayers as (...args: any[]) => any;
export const getPlayerTrackingStatuses = legacy_getPlayerTrackingStatuses as (...args: any[]) => any;
export const getPublicTrackingItems = legacy_getPublicTrackingItems as (...args: any[]) => any;
export const getRosterFieldDefinitions = legacy_getRosterFieldDefinitions as (...args: any[]) => any;
export const getTeam = legacy_getTeam as (...args: any[]) => any;
export const setTeamTrackingStatus = legacy_setTeamTrackingStatus as (...args: any[]) => any;
export const updateTeam = legacy_updateTeam as (...args: any[]) => any;
export const grantScorekeeperAccess = legacy_grantScorekeeperAccess as (...args: any[]) => any;
export const grantVideographerAccess = legacy_grantVideographerAccess as (...args: any[]) => any;
export const inviteAdmin = legacy_inviteAdmin as (...args: any[]) => any;
export const addTeamAdminEmail = legacy_addTeamAdminEmail as (...args: any[]) => any;
export const revokeScorekeeperAccess = legacy_revokeScorekeeperAccess as (...args: any[]) => any;
export const revokeVideographerAccess = legacy_revokeVideographerAccess as (...args: any[]) => any;
export const deactivatePlayer = legacy_deactivatePlayer as (...args: any[]) => any;
export const reactivatePlayer = legacy_reactivatePlayer as (...args: any[]) => any;
export const setPlayerPrivateRosterProfileFields = legacy_setPlayerPrivateRosterProfileFields as (...args: any[]) => any;
export const updateConfig = legacy_updateConfig as (...args: any[]) => any;
export const uploadPlayerPhoto = legacy_uploadPlayerPhoto as (...args: any[]) => any;
export const uploadTeamPhoto = legacy_uploadTeamPhoto as (...args: any[]) => any;
export const sendInviteEmail = legacy_sendInviteEmail as (...args: any[]) => any;
export const inviteExistingTeamAdmin = legacy_inviteExistingTeamAdmin as (...args: any[]) => any;
export const collection = legacy_collection as (...args: any[]) => any;
export const db: unknown = legacy_db;
export const doc = legacy_doc as (...args: any[]) => any;
export const getDoc = legacy_getDoc as (...args: any[]) => any;
export const getDocs = legacy_getDocs as (...args: any[]) => any;
export const query = legacy_query as (...args: any[]) => any;
export const serverTimestamp = legacy_serverTimestamp as (...args: any[]) => any;
export const setDoc = legacy_setDoc as (...args: any[]) => any;
export const updateDoc = legacy_updateDoc as (...args: any[]) => any;
export const where = legacy_where as (...args: any[]) => any;
export const normalizeRosterFieldDefinitions = legacy_normalizeRosterFieldDefinitions as (...args: any[]) => any;
export const splitRosterProfileValuesByVisibility = legacy_splitRosterProfileValuesByVisibility as (...args: any[]) => any;
export const validateRosterProfileValues = legacy_validateRosterProfileValues as (...args: any[]) => any;
export const describeScheduleReminderWindow = legacy_describeScheduleReminderWindow as (...args: any[]) => any;
export const normalizeScheduleNotificationSettings = legacy_normalizeScheduleNotificationSettings as (...args: any[]) => any;
export const calculateSeasonRecord = legacy_calculateSeasonRecord as (...args: any[]) => any;
export const listSeasonLabels = legacy_listSeasonLabels as (...args: any[]) => any;
export const computeNativeStandings = legacy_computeNativeStandings as (...args: any[]) => any;
export const buildPlayerLeaderboardSnapshot = legacy_buildPlayerLeaderboardSnapshot as (...args: any[]) => any;
export const normalizeStatTrackerConfig = legacy_normalizeStatTrackerConfig as (...args: any[]) => any;
export const selectAnalyticsConfig = legacy_selectAnalyticsConfig as (...args: any[]) => any;
export const getVisiblePlayerTrackingSummary = legacy_getVisiblePlayerTrackingSummary as (...args: any[]) => any;
export const normalizeTrackingStatus = legacy_normalizeTrackingStatus as (...args: any[]) => any;
export const hasFullTeamAccess = legacy_hasFullTeamAccess as (...args: any[]) => any;
export const normalizeAdminEmailList = legacy_normalizeAdminEmailList as (...args: any[]) => any;
export const buildTeamStaffPermissionsViewModel = legacy_buildTeamStaffPermissionsViewModel as (...args: any[]) => any;
export const buildTrackingStatusPayload = legacy_buildTrackingStatusPayload as (...args: any[]) => any;
export const summarizeTrackingStatus = legacy_summarizeTrackingStatus as (...args: any[]) => any;
