// @vitest-environment jsdom
import React from 'react';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const socialMocks = vi.hoisted(() => ({
    loadFriendProfile: vi.fn(),
    reactToSocialPost: vi.fn()
}));

vi.mock(import('../../apps/app/src/lib/socialService.ts'), () => socialMocks);

import { FriendProfile } from '../../apps/app/src/pages/FriendProfile.tsx';

const auth = {
    user: {
        uid: 'user-1',
        email: 'parent@example.com',
        displayName: 'Pat Parent',
        photoUrl: null
    },
    loading: false,
    error: null
};

function post({ id, title, createdAt, liked = false, likes = 0 }) {
    return {
        id,
        type: 'manual_post',
        visibility: 'friends',
        authorId: 'friend-1',
        authorName: 'Jamie Friend',
        authorPhotoUrl: null,
        teamId: null,
        teamName: null,
        playerIds: [],
        playerNames: [],
        sourceType: null,
        sourceId: null,
        title,
        detail: '',
        caption: null,
        media: [],
        route: null,
        href: null,
        createdAt,
        reactionCounts: { like: likes },
        commentCount: 0,
        viewerHasLiked: liked,
        hidden: false,
        autoGenerated: false
    };
}

function renderProfile() {
    return render(
        <MemoryRouter initialEntries={['/people/friend-1']}>
            <Routes>
                <Route path="/people/:userId" element={<FriendProfile auth={auth} />} />
            </Routes>
        </MemoryRouter>
    );
}

beforeEach(() => {
    vi.clearAllMocks();
    socialMocks.loadFriendProfile.mockResolvedValue({
        userId: 'friend-1',
        name: 'Jamie Friend',
        photoUrl: null,
        sharedTeamNames: ['Bears'],
        isSelf: false,
        posts: [
            post({ id: 'new-post', title: 'Newest update', createdAt: new Date('2026-07-17T12:00:00Z'), likes: 2 }),
            post({ id: 'old-post', title: 'Older update', createdAt: new Date('2026-07-16T12:00:00Z') })
        ]
    });
    socialMocks.reactToSocialPost.mockResolvedValue({ liked: true, count: 3 });
});

afterEach(() => cleanup());

describe('Friend profile page', () => {
    it('renders friend context and a newest-first timeline with working likes', async () => {
        renderProfile();

        expect(await screen.findByRole('heading', { name: 'Jamie Friend' })).toBeTruthy();
        expect(screen.getByText('Connected through Bears')).toBeTruthy();
        const newest = screen.getByRole('heading', { name: 'Newest update' });
        const older = screen.getByRole('heading', { name: 'Older update' });
        expect(newest.compareDocumentPosition(older) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();

        fireEvent.click(screen.getByRole('button', { name: 'Like post, 2 likes' }));

        await waitFor(() => expect(screen.getByRole('button', { name: 'Unlike post, 3 likes' })).toBeTruthy());
        expect(socialMocks.reactToSocialPost).toHaveBeenCalledWith('new-post', auth.user, 'like');
    });

    it('shows a friend-safe unavailable state when access is rejected', async () => {
        socialMocks.loadFriendProfile.mockRejectedValueOnce(new Error('This profile is available to accepted friends only.'));
        renderProfile();

        expect(await screen.findByRole('heading', { name: 'Profile unavailable' })).toBeTruthy();
        expect(screen.getByText('This profile is available to accepted friends only.')).toBeTruthy();
        expect(screen.getByRole('link', { name: 'Back to friends' }).getAttribute('href')).toBe('/home?section=friends');
    });

    it('is wired into the protected people route and linked from friend/feed cards', async () => {
        const { readFileSync } = await import('node:fs');
        const appSource = readFileSync('apps/app/src/App.tsx', 'utf8');
        const homeSource = readFileSync('apps/app/src/pages/Home.tsx', 'utf8');

        expect(appSource).toContain('path="/people/:userId"');
        expect(appSource).toContain('<FriendProfile auth={auth} />');
        expect(homeSource).toContain('View ${friend.name}\'s profile');
        expect(homeSource).toContain('/people/${encodeURIComponent(item.authorId)}');
    });
});
