import { describe, expect, it } from 'vitest';

import {
    buildDerivedSocialFeedItems,
    buildFriendshipId,
    buildSocialHomeModel,
    filterSocialFeedItems,
    getSocialPostPresetForType,
    getSocialTypeLabel,
    mergeSocialFeedItems,
    normalizeSocialFriend,
    socialPostPresets
} from '../../apps/app/src/lib/socialLogic.ts';

function event(overrides = {}) {
    return {
        id: overrides.id || 'game-1',
        teamId: overrides.teamId || 'team-1',
        teamName: overrides.teamName || 'Bears',
        type: overrides.type || 'game',
        date: overrides.date || new Date('2100-06-01T18:00:00Z'),
        location: overrides.location || 'Main Gym',
        opponent: overrides.opponent || 'Falcons',
        title: overrides.title || null,
        childId: overrides.childId || 'player-1',
        childName: overrides.childName || 'Pat Star',
        myRsvp: overrides.myRsvp || 'not_responded',
        assignments: [],
        ...overrides
    };
}

function feedItem(overrides = {}) {
    return {
        id: overrides.id || 'post-1',
        type: overrides.type || 'manual_post',
        visibility: overrides.visibility || 'team',
        authorId: overrides.authorId || 'user-1',
        authorName: overrides.authorName || 'Pat Parent',
        teamId: overrides.teamId || 'team-1',
        teamName: overrides.teamName || 'Bears',
        playerIds: overrides.playerIds || [],
        playerNames: overrides.playerNames || [],
        sourceType: null,
        sourceId: null,
        title: overrides.title || 'Team update',
        detail: overrides.detail || 'Bears update',
        caption: overrides.caption || null,
        media: overrides.media || [],
        route: overrides.route || null,
        href: null,
        createdAt: overrides.createdAt || new Date('2100-06-01T18:00:00Z'),
        reactionCounts: {},
        commentCount: 0,
        autoGenerated: overrides.autoGenerated === true
    };
}

describe('React app social logic', () => {
    it('derives social feed prompts from home schedule, packets, players, and teams', () => {
        const home = {
            upcomingEvents: [
                event(),
                event({
                    id: 'practice-1',
                    type: 'practice',
                    title: 'Practice',
                    date: new Date('2100-06-02T18:00:00Z'),
                    practiceHomePacketSummary: '2 drills · 20 min'
                })
            ],
            players: [{
                teamId: 'team-1',
                teamName: 'Bears',
                playerId: 'player-1',
                playerName: 'Pat Star',
                nextEvent: event(),
                rsvpNeeded: 1,
                packetsReady: 1,
                openAssignments: 0,
                unreadCount: 0
            }],
            teams: [{
                teamId: 'team-1',
                teamName: 'Bears',
                role: 'Parent',
                sport: 'Basketball',
                photoUrl: 'https://img.example.test/bears.png',
                players: [],
                nextEvent: event(),
                eventCount: 2,
                unreadCount: 2,
                openActions: 2
            }]
        };

        const items = buildDerivedSocialFeedItems(home, 'user-1', 'Pat Parent', new Date('2100-05-30T12:00:00Z'));

        expect(items.map((item) => item.type)).toEqual(expect.arrayContaining([
            'upcoming_game',
            'practice_packet',
            'player_moment',
            'team_media'
        ]));
        expect(items.find((item) => item.type === 'practice_packet')).toMatchObject({
            title: 'Practice packet ready',
            route: '/schedule/team-1/practice-1?childId=player-1&section=game'
        });
        expect(items.find((item) => item.type === 'team_media').media).toEqual([
            expect.objectContaining({ type: 'image', url: 'https://img.example.test/bears.png' })
        ]);
    });

    it('sorts and filters feed items for parent-friendly sections', () => {
        const items = mergeSocialFeedItems(
            [
                feedItem({ id: 'older', type: 'manual_post', visibility: 'team', createdAt: new Date('2100-05-01T12:00:00Z') }),
                feedItem({ id: 'duplicate', title: 'Old duplicate', createdAt: new Date('2100-05-02T12:00:00Z') })
            ],
            [
                feedItem({ id: 'player', type: 'achievement', visibility: 'friends', playerIds: ['player-1'], createdAt: new Date('2100-06-03T12:00:00Z') }),
                feedItem({ id: 'media', type: 'team_media', media: [{ type: 'image', url: 'https://img.example.test/post.png' }], createdAt: new Date('2100-06-02T12:00:00Z') }),
                feedItem({ id: 'duplicate', title: 'New duplicate', createdAt: new Date('2100-06-04T12:00:00Z') })
            ]
        );

        expect(items.map((item) => item.id)).toEqual(['duplicate', 'player', 'media', 'older']);
        expect(items[0].title).toBe('New duplicate');
        expect(filterSocialFeedItems(items, 'players').map((item) => item.id)).toEqual(['player']);
        expect(filterSocialFeedItems(items, 'highlights').map((item) => item.id)).toEqual(['player', 'media']);
        expect(filterSocialFeedItems(items, 'friends').map((item) => item.id)).toEqual(['player']);
    });

    it('categorizes friendships and removes requested users from suggestions', () => {
        const accepted = normalizeSocialFriend({ id: 'friend-1', displayName: 'Jamie Friend' }, 'user-1', {
            id: buildFriendshipId('user-1', 'friend-1'),
            status: 'accepted',
            requesterId: 'user-1',
            recipientId: 'friend-1',
            memberIds: ['friend-1', 'user-1']
        });
        const incoming = normalizeSocialFriend({ id: 'friend-2', displayName: 'Casey Parent' }, 'user-1', {
            id: buildFriendshipId('user-1', 'friend-2'),
            status: 'pending',
            requesterId: 'friend-2',
            recipientId: 'user-1',
            memberIds: ['friend-2', 'user-1']
        });
        const suggestion = normalizeSocialFriend({ id: 'friend-2', displayName: 'Casey Parent' }, 'user-1');

        const model = buildSocialHomeModel({
            feedItems: [feedItem()],
            friendshipFriends: [accepted, incoming],
            suggestions: [suggestion, normalizeSocialFriend({ id: 'friend-3', email: 'new@example.com' }, 'user-1')],
            currentUserId: 'user-1'
        });

        expect(model.friends.map((friend) => friend.userId)).toEqual(['friend-1']);
        expect(model.incomingRequests.map((friend) => friend.userId)).toEqual(['friend-2']);
        expect(model.suggestions.map((friend) => friend.userId)).toEqual(['friend-3']);
        expect(model.metrics).toEqual({
            feedItems: 1,
            friends: 1,
            incomingRequests: 1,
            suggestions: 1
        });
        expect(getSocialTypeLabel('game_recap')).toBe('Game recap');
    });

    it('defines quick-share presets for the social composer instead of exposing raw post fields', () => {
        expect(socialPostPresets.map((preset) => preset.id)).toEqual([
            'player',
            'game',
            'photo',
            'practice',
            'achievement'
        ]);
        expect(getSocialPostPresetForType('player_moment')).toMatchObject({
            label: 'Player moment',
            defaultVisibility: 'friends',
            prefersPlayer: true,
            suggestions: expect.arrayContaining(['Proud of the effort today.'])
        });
        expect(getSocialPostPresetForType('team_media')).toMatchObject({
            label: 'Photo or video',
            defaultVisibility: 'friends_and_team',
            requiresMedia: true
        });
        expect(getSocialPostPresetForType('manual_post')).toMatchObject({
            id: 'player',
            type: 'player_moment'
        });
    });
});
