name: pr-preview

on:
  pull_request:
    types:
      - labeled

permissions: {}

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview-artifact:
    if: >-
      github.event.label.name == 'preview-requested' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/deploy-preview.yml
